name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/green-lynk-frontend

            git pull origin main

            npm install

            NODE_OPTIONS="--max-old-space-size=2048" npm run build

            sudo rm -rf /var/www/html/*

            sudo cp -r build/* /var/www/html/

            sudo systemctl reload nginx
